// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgUWQrgEbfaYxFoFW6CliLv7D9C2ZWis8',
    appId: '1:142186261779:web:c0a7bd4f4c55183e557ee6',
    messagingSenderId: '142186261779',
    projectId: 'step-counter-v001',
    authDomain: 'step-counter-v001.firebaseapp.com',
    storageBucket: 'step-counter-v001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMfjXMaOaKUGpJaBQHJsSLcO_i0R39XtE',
    appId: '1:142186261779:android:1f00dcc2dd484a2c557ee6',
    messagingSenderId: '142186261779',
    projectId: 'step-counter-v001',
    storageBucket: 'step-counter-v001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiwvQt9vr6Gpx8prMehnopYUPX5YSOtvA',
    appId: '1:142186261779:ios:0b0375dbd47e037a557ee6',
    messagingSenderId: '142186261779',
    projectId: 'step-counter-v001',
    storageBucket: 'step-counter-v001.firebasestorage.app',
    iosBundleId: 'com.example.stepCounter',
  );
}
